### ISSUE TITLE
map: if breakpoint values aren't in breakpoint order then the ordering is wrong and specificity is out

### ISSUE THREAD

**Issue by jameslnewell** [jameslnewell/styled-components-breakpoint#16]
```js
<Body size="lg" color={{desktop: 'primary.500', tablet: 'primary.100'}}>
```

Expected:
```css
@media (min-width: 36.0625em)
<style>…</style>
.gOOjhT {
    color: #ccf2ed;
}
@media (min-width: 75.0625em)
<style>…</style>
.gOOjhT {
    color: #00c0a5;
}
```

Actual:
```css
@media (min-width: 75.0625em)
<style>…</style>
.gOOjhT {
    color: #00c0a5;
}
@media (min-width: 36.0625em)
<style>…</style>
.gOOjhT {
    color: #ccf2ed;
}
```
